hanami/hanami.github.io

source/guides/getting-started.md
@jodosha Great work on the getting started guide!
I've given it a 'first pass' and made some changes. Please review and merge, if you are happy. 
I will review the guide again later on in more depth :smile:
=> Review and update Getting Started page

source/guides/index.md
http://www.csinaction.com/2014/10/10/multithreading-in-the-mri-ruby-interpreter/
=> Ruby uses native Threads

source/guides/views/templates.md
Fixed some small stuff I found while reading the guide
=> Fix small amount of markup and spelling in views/templates.md

source/guides/command-line/generators.md
- Spell error
- Wrong path
- Explicit `arch`
=> Error fixes and phrase proposition

source/guides/helpers/forms.md
- Missing the class attribute
- Wrong verb
=> Typo and error fixes

source/guides/helpers/overview.md
- `in` must be the verb form `is`
- I would use `you` instead of `we`
=> Typo corrections

source/guides/getting-started.md
- Add helpful tips regarding `DATABASE_URL` format
- Generic `DATABASE_URL` format
- Linux Tip
=> Improve database config tips in getting started

source/guides/actions/overview.md, source/guides/getting-started.md
=> Fix some typos

source/guides/models/entities.md
Pull request to get started with contributions.
=> Minor typos

source/guides/actions/basic-usage.md, source/guides/actions/control-flow.md, source/guides/actions/cookies.md, source/guides/actions/exception-handling.md, source/guides/actions/exposures.md, source/guides/actions/http-caching.md, source/guides/actions/mime-types.md, source/guides/actions/overview.md, source/guides/actions/parameters.md, source/guides/actions/rack-integration.md, source/guides/actions/sessions.md, source/guides/actions/share-code.md, source/guides/command-line/applications.md, source/guides/command-line/database.md, source/guides/command-line/generators.md
Fixed some unnecessary commas and minor grammatical issues.  Expanded a few things to further clarify.
=> Various grammatical fixes and minor clarifications.

source/guides/command-line/generators.md
Describe model generator and the --skip-view option of the action generator.
=> Improve generators Command Line guide

source/guides/helpers/html5.md
div 'hello' will render <div>hello</div>
=> closing tag "</hello>"

source/guides/actions/http-caching.md
Removed `http_caching true` line
=> Remove wrong line

source/guides/getting-started.md
- add missing `action` variable
- cleanup DB before starting tests
- use `BookRepository` to check if a record was created since calling
`action.book` won't work. `book` isn't an instance variable and isn't
exposed by the controller and doesn't have to be.
=> Fix book create action specs in getting started guide

source/layouts/home.erb
Waiting for official endorsement letter
cc @jodosha
=> Remove Envato logo

index.html
=> Change `gc' to `git commit'

source/guides/actions/parameters.md
=> Enable syntax highighting of a codeblock

source/_footer.erb, source/atom.xml.erb, source/community.html.erb
I switched to HTTPS as a preferred link version and I fixed a broken link in the feed.
=> Fixed to various links

source/guides/views/templates.md
I not found this information in guides but I think that it's very useful.
=> Add information about nested templates

source/guides/views/templates.md
=> Fix #125 PR

source/stylesheets/application-minimal.css
=> Set grey color for command output in dev block

.travis.yml, README.md
Automating the deployment process on the merging of PRs
Adapt from https://iamstarkov.com/deploy-gh-pages-from-travis/
=> Auto-deploy to production

source/guides/helpers/html5.md
Reference https://github.com/hanami/helpers/issues/48
/cc @joneslee85, @jodosha
=> Add information about supporting link_to method

source/guides/getting-started.md
I think this is what we want.
This also changes 'totally beginner' to 'total beginner', since I think that's more natural.
=> Getting Started: change 'either' to 'whether' in lead note

source/layouts/home.erb
=> Fix typos on homepage

source/guides/getting-started.md
Fixed a typo in the getting started guide.
=> "Patterns of Enterprise Application Architecture" is PoEAA

source/_head.erb
A tiny tiny fix, that I'm not even sure shows up anywhere. ¯ \\_(ツ)_/ ¯
=> Fix title to not repeat 'Hanami'

config.rb, lib/github_style_titles.rb, source/stylesheets/guides.css
/cc @hanami/core-team and @hanami/contributors
=> Create anchors like in github

source/guides/actions/overview.md
Sorry, I did not add whitespace to search and replace regexp so I missed some chunks.
=> Same as #184, use <code> inside html tag

source/community.html.erb
I started a Local User Group here in São Paulo city (Brazil) to bring together all interested people in Hanami.
/cc @jodosha
=> Added Sao Paulo User Group into Community page

config.rb, source/layouts/guides.erb
Thanks for merging previous PR!
I wrote some code to add link to next page. I didn't add "prev" link because some guides already have link to previous page. I guess it doesn't matter because "prev" link is less important than "next" link.
I hope you like this :)
=> Add guide link to next page

source/guides/getting-started.md, source/guides/models/repositories.md
Updates guides to be up to date with new model, changes where introduced in https://github.com/hanami/model/issues/290
=> class methods => instance methods

source/guides/getting-started.md, source/guides/models/repositories.md
Reverts hanami/hanami.github.io#196
=> Revert "class methods => instance methods"

source/stylesheets/guides.css
=> Set colors for code a bit dingier

source/guides/getting-started.md
Reverts hanami/hanami.github.io#193
=> Revert "Update BookRepository methods calls"

source/stylesheets/application-minimal.css
=> Make footer text more lighter

source/guides/upgrade-notes/v080.md
Added Instruction to v.0.8 upgrade that the variable adapter -> uri must be modified
Updated instruction to edit .env.* files for clarity.
=> Added Missing Instruction to v.0.8 upgrade

source/guides/getting-started.md
Remove note about there being no `else` in the conditional, since we have one now.
Also add some information about what happens on both sides of the branch.
Fixes #207.
Feel free to provide feedback about tiny or subtle things :)
=> Fix 'Getting Started' note about 'else'

source/guides/views/custom-error-pages.md
=> Fix grammar in Custom Error Pages guide

source/guides/getting-started.md
I was just running each step of the guide to see how hanami works and found this little missing part on the bookshelf examples.
To make the test pass it  needs a div with an id equal to "books" wrapping each book div.
=> Fixing example in getting-started guide

source/guides/views/basic-usage.md, source/guides/views/overview.md
While reading the "basic usage" guide I found some awkward copy and thought I'd try to improve it for future readers. Hopefully the reworded statements successfully convey their intended meaning. :smile:
=> Edit copy in some View guides for grammar, clarity

source/guides/views/layouts.md
This PR adds a tutorial and an example case of using multiple templates in Hanami.
It took me a second to figure out how to include multiple templates in Hanami. I think this will be very useful to people coming from Rails who assume you can magically define templates and use them.
=> Update layout.md to explain how to use multiple templates

source/images/scroll_arrow.svg, source/javascripts/application.js, source/layouts/guides.erb, source/stylesheets/application-minimal.css
This PR implements #226 
See [this comment](https://github.com/hanami/hanami.github.io/issues/226#issuecomment-260208490) to see the final result.
cc @hanami/core-team @hanami/contributors
=> Add select for mobile guides for better experience

source/_footer.erb
=> Add hanami awesome to community list

source/guides/getting-started.md
=> Use SQLite in the Getting Started guide

source/guides/getting-started.md
reference to https://github.com/hanami/hanami.github.io/issues/239
/cc @hanami/core-team @hanami/contributors
=> Update information about entity in getting start guide

source/guides/architecture/overview.md
=> Update an outdated sentence on architectures guide

source/guides/getting-started.md
* Ensure spec label is consistent with previous example
* Clarify comment on omitting existing spec from code example
=> Fix Add a book spec title and comment

source/community.html.erb
change sentence about community attributes and correct small mistake
=> change community attributes

source/guides/models/repositories.md
=> repository count documentation

source/guides/models/associations.md
=> Update association example

source/guides/actions/control-flow.md
=> Redirect to back commented

source/guides/actions/http-caching.md
/cc @hanami/documentation @cllns
=> Add 'include' and 'require' right module to cache guide

source/layouts/home.erb
Setting db to postgresql fixes problems with deploy on heroku. Problem mentioned in #269
=> set database to postgresql in download, develop, deploy in 5 minutes section

source/guides/helpers/routing.md
I guess I found a small mistake in the routes doc.
=> web/apps => apps/web

source/guides/actions/testing.md
=> Add information how to test action flash messages

source/blog/2017-02-14-announcing-hanami-100beta1.html.markdown, source/guides/command-line/generators.md, source/guides/getting-started.md, source/guides/mailers/delivery.md, source/guides/projects/logging.md
=> Clean up #275

source/_footer.erb
=> Add link to hanami reddit

source/guides/models/associations.md
I'm fixing typos as I find them while reading the docs, I hope that's okay :) I'm really enjoying Hanami so far, great job with both documentation and overall design! Thank you!
=> Fix typo in association docs

source/guides/routing/basic-usage.md
I found a typo on Named Routes and I fixed it 🖊
=> Fix routing on Named Routes

config.rb, source/blog.html.erb
Closes https://github.com/hanami/hanami.github.io/issues/293
=> Add pagination to blog

source/guides/models/associations.md, source/guides/models/data-types.md, source/guides/models/entities.md, source/guides/models/overview.md, source/guides/models/postgresql.md, source/guides/models/repositories.md
I noticed a couple things that needed to be fixed, and decided to look through all the models guides and clean them up too :)
=> Clean up language on models guides

source/_footer.erb
=> Add link to hanami contributors site

source/guides/models/overview.md
The model generator also creates a migration.
=> Fix doc about model generator

source/guides/architecture/overview.md
Some grammar changes for flow and clarity.
=> Update overview.md with some grammar changes

source/guides/views/testing.md
I'm working on my first project in Hanami and I ran into this same issue quite quickly: https://github.com/hanami/helpers/issues/71
Since it took me a bit of time to figure out what is going on I thought it might be avoided for people trying hanami in the future by tweaking the guides a bit.
=> Mention the need to defined params in exposures in tests

source/guides/views/testing.md
=> Clean up for #317

source/guides/getting-started.md
The sentence I removed gived me impression that I should learn rails first and then come back to hanami. From reddit I understand that this is not correct. I'm intersted in hanami even when I never touched rails.
=> Removed misleading sentence from opening paragraph

source/guides/projects/initializers.md, source/guides/routing/overview.md
"Or" makes the subject a singular subject, so the helping verb "is" should be used.
=> Fixed grammatical errors in projects/initializers.md and routing/overview.md

source/_footer.erb
🎉 
I think we should start use [docs](http://hanamirb.org/docs/) project as soon as possible.
=> Add link to docs site

.travis.yml
=> Try to update middleman build

source/guides/helpers/forms.md
Solving https://github.com/hanami/hanami.github.io/issues/345
=> add description for fields_for_collection

source/guides/views/share-code.md
Reference to gitter disscussion https://gitter.im/hanami/chat?at=58f87d64f22385553d5b75b8
=> Update shared view guide

source/guides/views/share-code.md
See https://github.com/hanami/hanami.github.io/pull/319#issuecomment-313140109
=> Improve views shared code guide.

source/guides/routing/overview.md
It makes more sense for *Rack* description to be before *Actions*.
=> Structural improvements to overview.md

config.rb
Hi! Just a small performance update.
```ruby
random = rand(10_000..100_000)
array = Array(1..random);nil
Benchmark.ips do |benchmark|
fetch_random = rand(1..random)
benchmark.report('first(n)') { array.first(fetch_random);nil }
benchmark.report('[0...n]')  { array[0...fetch_random];nil }
benchmark.compare!
end
```
```sh
Warming up --------------------------------------
first(n)   170.343k i/100ms
[0...n]   139.688k i/100ms
Calculating -------------------------------------
first(n)      5.212M (± 9.3%) i/s -     25.892M in   5.028039s
[0...n]      2.878M (± 5.4%) i/s -     14.388M in   5.014773s
Comparison:
first(n):  5212370.8 i/s
[0...n]:  2878447.5 i/s - 1.81x  slower
```
=> Make retrieving articles a little bit faster

source/guides/head/command-line/applications.md
=> Add documentation for the hanami new --template option.

source/layouts/guides.erb
=> Fix selected dropdown guides page responsive site, Issue #367

source/guides/1.0/models/repositories.md
=> Add information about creating batch records

source/guides/head/models/database-configuration.md
Fixes https://github.com/hanami/model/issues/452
cc @nerdinand
=> Add jdbc info in database configuration page

source/guides/1.0/helpers/custom-helpers.md
To make readers understand better in the intro that they're going to make their custom helpers available to all of their views. What do you think? :)
=> Wording proposition

source/guides/1.0/assets/overview.md, source/guides/1.1/assets/overview.md
I was reading through this page and found a few places that could be tidied up to make more sense. I think I've retained the original meanings, just think it reads better this way.
Hope this is helpful!
=> Assets overview grammar

source/guides/1.1/projects/rake.md
I'm not sure if this is true, but it seems from the context.
=> Make clarification about the test/spec defaultness

source/guides/1.1/validations/custom-predicates.md
Ref https://github.com/hanami/validations/issues/129
=> Guides article for custom validations and I18n

source/guides/1.1/views/basic-usage.md
I haven't found any info about the fact, that you can access the values from the controller in the view. This is particularly important for views that want to wrap these values or convert them to other representation (e.g. JSON).
=> Accessing values exposed by the controller

Gemfile, Gemfile.lock
=> Update nokogiri version to fix CVE-2017-9050

source/guides/1.1/architecture/interactors.md
see: https://github.com/hanami/hanami.github.io/issues/435
=> WIP: Doc: fix code in Guides/1.1/Architecture/Interactors

source/guides/1.0/projects/logging.md, source/guides/1.1/projects/logging.md
Add info how to completely disable logging of params of requests.
=> No params logging howto

source/guides/1.1/models/use-your-own-orm.md
And also reformat the listing.
=> Add notes about removing from `spec` dir

source/guides/1.0/models/use-your-own-orm.md
I should've done this as part of #438, my bad! 
(cc @Pistos)
=> Update 'Use Your Own ORM' guide for 1.0

source/_footer.erb, source/privacy.html.erb
=> Privacy policy (GDPR)

source/guides/1.0/migrations/alter-table.md, source/guides/1.1/migrations/alter-table.md, source/guides/1.2/migrations/alter-table.md
Updated `alter_table` section:
- Added new example;
- Added list of available methods for usage without `alter_table` block;
=> Update usage of alter table methods

source/guides/1.1/repositories/overview.md
Adding some info on how to deal with legacy databases, the caveats of mapping and working with just a subset of the schema.
I'm open to suggestions.
=> Expands the info about legacy database support

source/guides.html.erb
---
Closes https://github.com/hanami/hanami.github.io/issues/484
=> Redirect traffic from /guides to guides.hanamirb.org

source/_navbar.erb
Link to API needs to be easier to find.
=> Add link to Hanami API Docs

source/status.html.erb
See https://github.com/dry-rb/dry-cli/pull/57
=> Remove `hanami-cli`

source/atom.xml.erb
=> Use html entity for extract

source/_hanami2.erb, source/_navbar.erb, source/stylesheets/application-minimal.css
=> Hanami 2.0 banner

source/blog/2021-05-04-announcing-hanami-200alpha2.html.markdown
I feel like a real open-source-contributor-pro with such PRs 😎
=> Fix smaller typo in the blog post
