hanami/hanami.github.io

- source/guides/migrations/overview.md
- source/layouts/guides.erb
1. I removed the link to the view partials guide, as it does not seem to exist. Correct me if i'm wrong :)
2. Fixed a link to the database command line guide in the Migration Overview article
> Remove view partials from navigation and fix link to database cmd line tools

- source/guides/getting-started.md
books table migration adds two columns (created_at, updated_at) which
have a null-constraint. To be able to persist `Book` objects we have
to add `created_at` and `updated_at` to `Book` entity attributes and
map them accordingly.
> Fix null-constraint violation exception in getting started guides

- source/guides/getting-started.md
According to the guide, this action purpose is to expose all books
to the view. It now compares exposed books to those available in
`BookRepository` rather than an empty array.
> Fix books controller specs for exposure in getting started guide

- source/guides/helpers/escape.md
- The `u` in `user` is pronounced as `y` and is therefore treated as a consonant: `a user`
- Same for `a URL` (see http://itknowledgeexchange.techtarget.com/writing-for-business/which-is-correct-a-url-or-an-url/)
- Missing pronoun `he`
> Typos and missing pronoun

- source/guides/actions/sessions.md
```ruby
module Web::Controllers::Dashboard
class Index
include Web::Action
def call(params)
sessions[:b]         # read
sessions[:a] = 'foo' # assign
sessions[:c] = nil   # remove
end
end
end
```
```ruby
module Web::Controllers::Dashboard
class Index
include Web::Action
def call(params)
session[:b]         # read
session[:a] = 'foo' # assign
session[:c] = nil   # remove
end
end
end
```
> FIXED: Correct use for session on controller

- source/guides/getting-started.md
The path listed in the code example to create_spec.rb seems to be wrong, no app directory exists within /spec/web path.
> Fixes comment that contains the absolute path to create_spec.rb

- source/guides/getting-started.md
- Adds describe block 
- Fix to reference `new.html.erb` template instead of `index.html.erb` 
- Adds `NewBookParams` class to example to stub out validation rules, and uses an instance of that instead of base ` Lotus::Action::Params`, which contains no validation rules.
Unsure if this is the blessed way of making this test pass, so this is my best guess.
> Fixes 'Displaying Validation Errors' spec example in the Getting Started Guide

- source/guides/getting-started.md
In the example first `redirect_to '/books'` is used.
Then after knowing the routes helper it is replaced with `redirect_to routes.books_url`.
This should be `redirect_to routes.books_path`
> Change to proper redirect

- source/guides/getting-started.md
When we generate an app with `lotus new` we create `:name/apps/web/templates/application.html.erb`. The guide then refers to `application.htm.erb`, which I think is a typo. :grinning:
> Fix typo in application layout filename

- source/guides/getting-started.md
Fix user and password location on db url and adds default port too.
Using the url from example, occurs:
`/home/roger/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/lotus-model-0.4.0/lib/lotus/model/migrator/adapter.rb:108:in `+': no implicit conversion of nil into String (Ty
peError)`
> Fix db connection with user and password

- source/guides/getting-started.md
Gemfile.lock is not created when a new application is generated.
> Remove Gemfile.lock from the new application directory stucture

- source/guides/getting-started.md
The 'with invalid params' scenario should have access to the action
variable.
> Fix let declaration in Getting Started guide

- source/guides/getting-started.md
This minor correction singularizes the word “projects” to “project” in the [_Using Repositories_](http://lotusrb.org/guides/getting-started/) guide.
> …we use env variables loaded from `.env` files. Our ~~projects~~ project has three of them…
:v:
> Singularize "projects" in repositories guide

- source/guides/getting-started.md
since you have already defined  `let(:rendered)  { view.render }` , there is no reason to use `view.render` again
> use correct instance variables from let

- source/guides/mailers/testing.md
Lotus::Mailer.deliveries returns an array. #last method is needed to
access mail object.
> fix mailer test

- source/guides/helpers/custom-helpers.md
Change the link to point to the correct `Views Share Code` section instead of `Actions Share Code`
> Fix Views Share Code link

- source/guides/architectures/container.md
- source/guides/getting-started.md
"*Clearly*, *obviously*, *naturally*, and *of course* all presume too much about the reader's knowledge and perspective and often amount to excess verbiage." - [Wikipedia Manual of Style](https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Words_to_watch#Editorializing)
Obviously (:wink:) we're not bound to Wikipedia's Manual of Style, but I think it's a good rule.
I left one 'actually', in the [Displaying Dynamic Data](https://github.com/lotus/lotus.github.io/blob/build/source/guides/getting-started.md#displaying-dynamic-data) of Getting Started, where it says *'If we run our feature test now, we'll see it fails — because our controller action does not __actually__ expose the books to our view'* because it seems useful.
> Remove words that presume knowledge

- source/guides/views/mime-types.md
This is one of the only examples of JSON output using lotus. The latest versions of Lotus do HTML safety by default. By adding the `raw` to the method call we give people exploring the docs a more "ready to copy-paste" example.
> Add raw to JSON render

- source/guides/getting-started.md
- source/guides/helpers/escape.md
We shouldn't use masculine pronouns by default. Instead we should be more inclusive by using neutral pronouns.
> Change masculine pronouns to neutral

- source/guides/getting-started.md
If the user decides to use a different adapter to `postgres` they will be thrown an error. This is also the case if the user sets up a new project without specifying an adapter.
In order to stop this happening, the adapter of their choice needs to be specified in the Gemfile, I have simply added a line to the get started documentation to outline this if the user decides to choose a different adapter they will need to add this to the Gemfile.
> Add adapter if not using postgres

- source/guides/command-line/generators.md
- source/guides/getting-started.md
Updates guides to reflect: lotus/lotus#404.
Also adds a note about `--method` because it's relevant
> Update guides to mention generated actions using RESTful HTTP methods

- source/guides/routing/restful-resources.md
Nested resource for single-to-plural and single-to-single showed routes for plural-to-plural and plural-to-singular. Replaced `/accounts/:account_id/` with `/account/` in each case so that the documentation shows the correct routes in each table.
Removed `:create_` from POST routes for nested resources (e.g. `:create_account_avatar` should just be `:account_avatar` with a POST method).
> Fix documentation for nested resource routes

- source/guides/getting-started.md
Validation specs weren't testing that the create action was really validating attributes but only that the user was redirected. A new spec ensure that the action is filled with expected errors.
It also fixes the spec which checks that the errors are displayed to the user. The current code can't work since `new` view doesn't know anything about `create` action. Both are isolated in tests. So I replaced it by a feature spec which can go through the whole process and really test for error displaying.
> Fix validation specs

- source/guides/helpers/custom-helpers.md
I spotted a minor syntax error in code snippet on page about custom helpers. This is a small fix for that.
> Fix syntax error in code snipper for custom helpers

- source/_lotus.erb
If you go to hananmirb.org right now, the page is slightly too wide. You can scrolls sideways a tiny bit.
This is because of the `lotus` partial, which has a row which has negative margins on left and right of `-10px`.
This PR fixes that by wrapping the `.row` div in a `.container` div.
> Add container around 'lotus' row

- source/stylesheets/guides.css
All of the ['guides' pages](http://hanamirb.org/guides/) have a 40px padding at the bottom of the body. We don't want that :)
> Remove padding-bottom from body on guides pages

- source/guides/command-line/generators.md
- source/guides/getting-started.md
Reference https://github.com/hanami/hanami/issues/489
> Add information about generation action with --method

- source/guides/models/overview.md
Fix unclosed code tag on the model overview page. It would create weird blocks around the code examples as they would be nested under another unclosed tag.
Before:
After:
> Fix unclosed code tag

- source/guides/applications/initializers.md
This line and the one after say exactly the same thing. I've removed this line because it is slightly less explicit than the alternative.
> Removes duplicate execution order statement

- source/guides/getting-started.md
In the past, it used to require the `--url=/path/to/action` parameter, but it doesn't modify anything anymore.
> Removed old generator's action parameter

- source/layouts/blog.erb
- source/layouts/guides.erb
- source/layouts/home.erb
- source/layouts/layout.erb
As a fix to #149 I suggest replacing the dead Feedburner links by link to the Atom feed generated by Middleman.
> link to Atom feed generated by Middleman

- source/guides/models/overview.md
I added 'IF NOT EXISTS' to the 'CREATE EXTENSION' line as that migration will fail if the extension is already created unless 'IF NOT EXISTS' is there as well.  It fails with an error as such:
```
/path/to/gem/lib/sequel/adapters/postgres.rb:186:in `async_exec': PG::DuplicateObject: ERROR:  extension "uuid-ossp" already exists (Sequel::DatabaseError)
```
> improve pgsql syntax in example

- source/guides/getting-started.md
I was going through [getting started](http://hanamirb.org/guides/getting-started/) guide and I noticed a small typo. "It" should be "If".
> Fix typo in 'getting started' guide

- source/guides/models/overview.md
Using:
```ruby
require 'hanami/model/coercer'
require 'sequel/extensions/pg_array'
```
Raise exception:
```
`<top (required)>': uninitialized constant Sequel (NameError)
from /Users/vyper/Documents/projects/guru-pr/c4p/lib/ext/pg_array.rb:2:in `require'
from /Users/vyper/Documents/projects/guru-pr/c4p/lib/ext/pg_array.rb:2:in `<top (required)>'
[...]
```
To solve I used:
```ruby
require 'hanami/model/coercer'
require 'sequel'
require 'sequel/extensions/pg_array'
```
> Fix require on custom coercions example

- source/guides/getting-started.md
I think this is what we want.
I use `zsh` (5.0.6) and I don't have this problem. Is this note necessary? Has anyone else run into this? This note was added in #94.
> Fix note about ZSH

- source/guides/getting-started.md
I noticed the output of `hanami routes` in the Getting Started guide wasn't accurate:
- The `'/'` route didn't have the `home` name
- The columns didn't have headers 
- The ordering was wrong (the `home` route was first, it should be at the bottom)
This PR fixes all those. 
Note: I removed a lot of the whitespace from the output of `hanami routes`. Here's what it actually looks like:
```
Name Method     Path                           Action
books GET, HEAD  /books                         Web::Controllers::Books::Index
new_book GET, HEAD  /books/new                     Web::Controllers::Books::New
books POST       /books                         Web::Controllers::Books::Create
book GET, HEAD  /books/:id                     Web::Controllers::Books::Show
edit_book GET, HEAD  /books/:id/edit …
```
> Fix order of routes, add column headers & add home name

- source/guides/helpers/forms.md
Add missing helper tags and inputs. Add documentation link to each heller. Add "Pass A Value" and "Share Code Between Views" examples.
> Update form helper documentation

- source/guides/actions/overview.md
Adds a warning to help people avoid / debug / fix constant lookup errors caused by using the same module name for an App and a Controller, as mentioned in hanami/hanami#561.
I'm a little unsure about multiple `<p class="warning">`s in a row, but in the GH preview output, wrapping the paras in a `<div class="warning">` just made the output vanish. (AFAICT there's nothing in the CSS that would cause a problem there in actual HTML, but I'm wary of introducing usage that just breaks useful reviewing tools.)
> Add warning about naming Controllers after Apps

- source/guides/routing/restful-resources.md
changed “manoscripts” to “manuscripts”, and fixed grammar in two places
> Fix spelling & grammar in RESTful Resources guide

- source/guides/actions/overview.md
Some code words on guides/actions/overview are not rendered the right way because "`"is used inside a HTML tag. 
`<code></code>` should be use instead.
> Fix code fragment inside html tags

- source/_footer.erb
- source/_navbar.erb
- source/layouts/blog.erb
- source/layouts/guides.erb
- source/layouts/home.erb
- source/layouts/layout.erb
- source/status.html.erb
- source/stylesheets/application-minimal.css
I found this idea on [ROM site](http://rom-rb.org/status/). Also I'll be very glad to any comments and suggestions 💚 
/cc @hanami/core-team and @hanami/contributors
> Add special page with status of all hanami parts

- config.rb
- data/guides.yml
- source/layouts/guides.erb
Refactor guides toc to use data instead of hard coding all links.
While reading a guide, I want to go to "next" (or "prev") page from the bottom of page like this (https://www.playframework.com/documentation/2.4.x/NewApplication), but they are hard coded. To generate the next page link automatically, I started with refactoring them. What do you think about this?
Thanks.
> refactor(guides) use data instead of hard coding

- source/guides/getting-started.md
I update the BookRepositoy.method to BookRepository.new.method
According to the https://github.com/hanami/model/blob/master/README.md
The Repository methods are now instance methods instead of class methods
> Update BookRepository methods calls

- source/guides/getting-started.md
Following the "getting started" guide, [this test](https://github.com/hanami/hanami.github.io/blame/e975e70358a5a7da48387bd8722081d3861a8aa4/source/guides/getting-started.md#L790) failed:
```
1) Failure:
Web::Controllers::Books::Create#test_0001_creates a new book [/files/alter/workspace/bookshelf/spec/web/controllers/books/create_spec.rb:17]:
Expected: nil
Actual: "Confident Ruby"
```
And that's because after call `action.call(params)`, the `params` var is changing from this:
```
[1] pry(#<Web::Controllers::Books::Create>)> params
=> {:book=>{:title=>"Confident Ruby", :author=>"Avdi Grimm"}}
```
into this:
```
[3] pry(#<Web::Controllers::Books::Create>)> params
=> {:book=>{"title"=>"Confident Ruby", "author"=>"Avdi Grimm"},
"hanami.action"=> …
```
> Using string instead of symbol to call key

- source/guides/getting-started.md
I came across these when doing a fresh run through the Getting Started guide with the released 0.8.0 update to the guide. Here's the code from the guide if you want to verify that the tests pass with these changes: https://github.com/bruz/bookshelf-delivery-example/tree/getting-started-guide (note it's on the `getting-started-guide` branch).
> Fix validation tests in getting started guide

- source/guides/models/overview.md
Since the text “MUST” is within `<p>` HTML tags, it must be marked up with `<strong>…</strong>` HTML tags instead of `**…**` Markdown syntax.
That section on the live site: http://hanamirb.org/guides/models/overview/#custom-coercions
> Fix bold markup in Model Overview guide

- source/guides/getting-started.md
Small consistency fix for code examples in Getting Started guide.
> Always use single quotes in code examples

- source/guides/getting-started.md
- source/guides/views/layouts.md
1. Standardize how we title our sections (we don't need to follow any particular style guide, but here's the APA's rule: http://blog.apastyle.org/apastyle/2012/03/title-case-and-sentence-case-capitalization-in-apa-style.html)
2. Update number of assertions / runs for tests, based on current Getting Started guide
3. Standardize `<!doctype HTML>` to `<!DOCTYPE HTML>`, since that's more popular and it's what our generators do.
4. Clarify what Gemfile does in simpler terms
> Clean up 'Getting Started' guide

- source/guides/routing/basic-usage.md
- source/guides/routing/testing.md
It seems support for `Web::Routes` references was dropped (accidentally?) in 0.9.0 or later. This change updates the documentation to provide the style of reference that now works: `Web.routes`.
If this was an intentional change, we should probably also update the [upgrade notes](http://hanamirb.org/guides/upgrade-notes/v090/). I'm happy to include that in this PR if so.
> Replace uses of `Web::Routes` with `Web.routes`

- source/guides/models/repositories.md
That should be `repository`, if I'm not mistaken.
> Guides on Repositories: fix typo on source code example.

- source/_footer.erb
- source/stylesheets/application-minimal.css
Hey, I added [sidecar](https://sidecar.gitter.im) to our index page. I can add this to all pages but I think it will be unnecessary. What do you think?
/cc @jodosha @cllns @hanami/contributors
> Add gitter chat on index page

- source/blog/2015-06-23-announcing-lotus-040.html.markdown
- source/blog/2016-02-05-announcing-hanami-071.html.markdown
- source/guides/views/mime-types.md
This PR fixes a grammar mistake on `source/guides/views/mime-types.md`.
More info about this piece of grammar can be found [here](http://www.anglaide.com/before-to/).
The same mistake happens [here](https://github.com/hanami/hanami.github.io/blob/build/source/blog/2015-06-23-announcing-lotus-040.html.markdown), and [here](https://github.com/hanami/hanami.github.io/blob/build/source/blog/2016-02-05-announcing-hanami-071.html.markdown), however I am not sure if fixing it is necessary as they are previous blog entries. 
I can quickly fix them if necessary.
> 'Before to' grammar mistake fix

- source/guides/models/associations.md
Small typos I found while reading through the docs for the first time
As I am very new to Hanami, can someone confirm that the `where` clause correction makes sense? Thanks.
> Small Typos in Associations Guide

- data/guides.yml
- source/guides/database-configuration/overview.md
- source/guides/models/database-configuration.md
When generated a new Hanami project with PostgreSQL I was a bit confused how to setup a database on my local machine (I was not able to start `hanami server` because of database connection error). It's not well documented yet so I spend some time to find the answer.
I'm not sure where is the best place to show the setup instructions but I hope it will be helpful for new Hanami users.
Particularly closes #229.
Cheers!
> Add instructions to setup PostgreSQL

- source/guides/routing/overview.md
The mounting guide explains how to mount to a path and a subdomain but does not
explain where the mount code should live.  Rails mounts within the route config
but Hanami mounts within the environment config.  The difference is worth
documenting.
Fixes #245
> Add detailed information on mounting applications

- source/guides/command-line/database.md
- source/guides/getting-started.md
This commit is intended to help people with setting up their database to run their tests.
Hanami is all about TDD / BDD and there's a strong emphasis on how to write tests but there's a missing part about how to configure the test database so new comers can be stuck with an error message telling them that a database is missing even if they followed the getting started guide step by step.
With these explanation the gap is filled.
> Add instructions about how to setup test database

- source/guides/command-line/applications.md
Currently, the default of `database` is SQLite.
> Fix doc for `database` argument

- source/guides/getting-started.md
Thank you for your nice documents.
I found a small improvement in the Getting Started page.
I think it is better to use a word `initialize` instead of `initialise` because the previous description (... which we pass to initialize params) uses it.
Also, `initialize` is a very popular method name in Ruby.
> Use a word 'initialized' instead of 'initialised'

- source/guides/mailers/basic-usage.md
There were a couple small typos in the mailer guide. I hope this helps 👍 
Congrats on 1.0!
> Fix some typos in the Mailer Basic Usage guide

- source/guides/architecture/overview.md
- source/guides/command-line/applications.md
Architecture flag is not supported and Hanami supports only container architecture.
> Architecture paragraph was removed from command-line guide

- source/guides/getting-started.md
By following the guide and using the `books_url` routes helper, instead of `books_path`, the action test fails:
```
1) Failure:
Web::Controllers::Books::Create::with valid params#test_0002_redirects the user to the books listing [/home/tpavel/workspace/bookshelf/spec/web/controllers/books/create_spec.rb:27]:
Expected: "/books"
Actual: "http://0.0.0.0:2300/books"
```
I see `books_path` is used in the corresponding commit in the [hanami/bookshelf repo](https://github.com/hanami/bookshelf/commit/7a99bb50a87449d2e9794a2498de751f4fc9b4a7), so this PR should keep things consistent.
> avoid test failure by using books_path

- source/guides/upgrade-notes/v100.md
See https://github.com/hanami/hanami/issues/767
@jodosha turns out one could also remove the line specifying the mailer root folder.
I think a simple inline hint should suffice. WDYT?
> Add hint that mailers folder is now required

- source/guides/getting-started.md
Related PR: #320
As discussed in previous PR, the expectation for redirect location should be strict and consistent across versions of the test before and after refactoring.
> use consistent expectation for redirect location

- source/guides/getting-started.md
As @sheldonh in the hanami chat mentioned, the instruction in the getting started guide do not explicitly state to prepare the test database. When one sticks to the guide the test therefore fails.
See [his message from 28. April 2017 14:14](https://gitter.im/hanami/chat?at=5903320b12d2409935a8c34d)
Since both the development and test database need to be prepared for the subsequent parts of the getting started guide to work properly, I suggest to apply the changes of this PR.
> Instruct to prepare test db before entity tests

- source/guides/helpers/forms.md
Hi! I found a unexpected italic style in `forms.md`. (This is due to lack of escape)
I hope this helps.
> fix unexpected italic in forms.md

- source/guides/helpers/html5.md
The link to Escape Helpers page is broken on HTML5 helpers page.
See http://hanamirb.org/guides/helpers/html5/
- Broken link: http://hanamirb.org/guides/helpers/html5/%60/guides/helpers/escape%60 (404 page)
- Correct link: http://hanamirb.org/guides/helpers/escape/
> Fix Escape Helpers link in Guides HTML5 Helpers

- source/guides/models/entities.md
The email used for instantiating User was not matching the expected email.
We're now using `luca@hanami.test` everywhere.
```ruby
user = User.new(name: "Luca", age: 34, email: "test@hanami.test")
user.email    # => "luca@hanami.test"
```
```ruby
user = User.new(name: "Luca", age: 34, email: "luca@hanami.test")
user.email    # => "luca@hanami.test"
```
> Fix example of Entity instantiation

- source/guides/actions/request-and-response.md
Small typo here, we should use `accept?` method instead of `accepts?` method: there is no `s`.
I'm new to the framework so here I guess it refers to this method 👉 https://github.com/hanami/controller/blob/master/lib/hanami/action/mime.rb#L488-L492
> Fix Guides - Request and Response page

- source/guides/getting-started.md
I was going through the guide and this part surprised me
> As you can see, in this case we simply hard-code the error message "is required", but you could inspect the error and customise your message for the specific validation that failed
because the guide didn't hardcode "is required" it looped over `param.errors` and showed proper error messages.
Wasnt sure what to replace it with, so I copy pasted the "run your tests again" message from the section above since the code snippet below is running the tests.
> Update getting started guide

- source/guides/getting-started.md
> Fix formatting for 'hanami routes' command output

- source/donate.html.erb
Hallo all!
I'm adding Creditas (with logo) and myself (link only) as donators on Donation page.
I was wondering how could be the _best_ way to place Creditas' logo there and did using `<p>` inside `<div>` - not sure if it's the best way™ to do so.
This is how it is now:
Thoughts? 💯
> Added hlegius and Creditas as donators

- source/guides/head/projects/logging.md
Just fulfilling this request: https://github.com/hanami/hanami/pull/768#pullrequestreview-34588664
This adds a custom logger example that the referenced PR enables. By the way, we ❤️  hanami at [Timber](https://timber.io). We have a lot of happy customers using it.
> Add custom logger example

- source/guides/1.0/migrations/overview.md
- source/guides/head/migrations/overview.md
On [Migration Overview](http://hanamirb.org/guides/1.0/migrations/overview/) page, just make sure that the link to the **migration generator** goes directly at the `#migrations` anchor, [here](http://hanamirb.org/guides/1.0/command-line/generators/#migrations).
I made the change for both `1.0` and `head` versions.
> Update link to migration generator

- source/guides/1.0/helpers/routing.md
- source/guides/head/helpers/routing.md
I was searching on how to configure `host` and other settings for absolute URLs. But when using the search form and searching for `url` or `absolute urls`, it points only to  [Routing helpers](http://hanamirb.org/guides/1.0/helpers/routing/) page. 
On this page, there is no mention on how absolute URLs are generated: using `scheme`, `host` and `port` settings.
I updated this page by taking the sentence from [Routing - basic usage](http://hanamirb.org/guides/routing/basic-usage/#named-routes) page.
Sometimes the information is there but not exactly where we are looking at =)
> Update Routing helpers in guides

- source/guides/1.0/actions/control-flow.md
- source/guides/head/actions/control-flow.md
There is no method `request#headers[]` according to below.
- https://github.com/hanami/controller/blob/master/lib/hanami/action/request.rb
- http://www.rubydoc.info/gems/rack/Rack/Request/Env#get_header-instance_method
So, I fixed the example to valid one.
> Fix incorrect usage in guides/actions/control_flow

- source/guides/1.0/views/share-code.md
- source/guides/head/views/share-code.md
In the example on the [Views share code](http://hanamirb.org/guides/1.0/views/share-code/) page, the shared file is stored at `apps/web/views/accept_json.rb` and we require it from `apps/web/application.rb`.
Thus the require relative is not pointing at the correct path, it's missing the `views` folder.
I've updated both 1.0 and head versions.
> Fix share code page in Views guide

- source/guides/1.0/migrations/create-table.md
- source/guides/head/migrations/create-table.md
- source/stylesheets/guides.css
When looking for wich data type I can use in a migration, I know that it must be somewhere in the Migrations section. And yes, I find the information here in the [Migrations create table](http://hanamirb.org/guides/1.0/migrations/create-table/) page.
But I keep forgetting that there are extra data types for PostgreSQL that are mentionned elsewhere, here in [Models PostgreSQL](http://hanamirb.org/guides/1.0/models/postgresql/).
So I've added a mention to this page on **Migrations create** table page.
BTW does it make sense to have [PostgreSQL](http://hanamirb.org/guides/1.0/models/postgresql/) page inside the **Models** category? From what I see, it's mostly about PostgreSQL migrations. What do you think?
PS: the default purple link didn't look nice inside the convention paragraph. I …
> Mention PostgreSQL types in Migration data types page

- source/guides/1.0/models/repositories.md
- source/guides/head/models/repositories.md
- source/stylesheets/guides.css
I'm often struggling to create rather "complex" SQL queries (eg. joins, order desc, average, etc.) with Hanami repository. And I often end up with a mix of ROM and exceptionally Sequel syntax (eg. when having to qualify a column).
I think it could be nice to provide links to ROM and Sequel documentations in the [Repository](http://hanamirb.org/guides/1.0/models/repositories/#private-queries) guide as mentioned here https://github.com/hanami/hanami.github.io/issues/309#issuecomment-300313160
Here is a screenshot of the block I've added 👇
> Add mention to ROM and Sequel in Repositories guide

- config.rb
Compass is not being used thus it could be safe to remove. Plus compass is extracted to middleman-compass in v4 of compass due to its stagnation in development and support.
> Remove unused compass config

- source/guides/1.0/models/repositories.md
- source/guides/head/models/repositories.md
Quick fix in [Repositories](http://hanamirb.org/guides/1.0/models/repositories/#timestamps) guide. 
It should be "take care of keeping" instead of "take care of keep".
> Fix typo in Repositories guide

- source/team.html.erb
https://twitter.com/marionschleifer leads to a 404. 
I think it would be this one: https://twitter.com/rubydwarf her valid account.
> Fix link to Marion Schleifer's twitter on Team page

- source/guides/1.0/migrations/alter-table.md
- source/guides/1.0/migrations/create-table.md
- source/guides/head/migrations/alter-table.md
- source/guides/head/migrations/create-table.md
Currently, all of the pages related to migrations have the same h1 which is
"Migrations". It should be more specific to the topic of the page.
Plus make sure that levels are consistent. Below is an overview of the structure proposed in this pull request.
For [Create table](http://hanamirb.org/guides/1.0/migrations/create-table/):
- H1: Create Tables
- H2: Column Definition
- H2: Type Definition
- H3: Options
- H2: Primary Key
- H2: Foreign Keys
- H3: Options
- H2: Indexes
- H3: Options
- H2: Constraints
- H2: Checks
And for [Alter table](http://hanamirb.org/guides/1.0/migrations/alter-table/):
- H1: Alter Tables
- H2: Rename Table
- H2: Drop Table
I tried to respect the same structure as on the other pages (eg. [Models entities](http://hanamirb.org/guides/1.0/models/entities/))
> Update levels of titles in Migrations guides

- source/guides/models/repositories.md
Reference to https://github.com/hanami/model/issues/380
/cc @hanami/documentation @cllns @jodosha
> Update documentation for repository last and second methods

- data/guides.yml
- source/guides/models/query-examples.md
Reference to https://github.com/hanami/hanami.github.io/issues/343
> [wip] Create repository query guide with examples

- source/guides/1.1/assets/content-delivery-network.md
By default, Hanami does not allow the execution of JavaScript from external sources. This small paragraph explains why and shows how to modify the settings. It is kept short in order to not make it redundant with the contents of the security guide (once someone expands it).
> About Content Security Policy settings and CDNs

- source/layouts/home.erb
> Center aligning company logos for more space between them

- source/guides/1.0/mailers/delivery.md
- source/guides/1.1/mailers/delivery.md
This PR fixes an error on the [Mailer Custom Method](http://hanamirb.org/guides/1.0/mailers/delivery/) documentation.
```ruby
mailer do
production MandrillDeliveryMethod, api_key: ENV['MANDRILL_API_KEY']
end
```
```ruby
mailer do
delivery MandrillDeliveryMethod, api_key: ENV['MANDRILL_API_KEY']
end
```
> Fix mailer custom delivery method example

- source/guides/1.0/models/use-your-own-orm.md
- source/guides/1.1/models/use-your-own-orm.md
* Add missing info about need to delete `require 'hanami/model'`
* Add note stating that `bookshelf` should be name of the project in
practice
> Improve section about using own ORM

- source/guides/1.1/repositories/postgresql.md
Instead of uuid-ossp extension, pgcrypto seems to be recommended.
See [postgresql 9.4 documentataion](https://www.postgresql.org/docs/9.4/static/uuid-ossp.html#AEN170626) and newer versions for detail.
> Prefer "pgcrypto" to "uuid-ossp"

- source/guides/1.2/architecture/overview.md
I found out two errors on links while reading the guide
> Fix 404 in architecture overview

- .travis.yml
Travis supports deploy to GH pages as a [first-class feature](https://docs.travis-ci.com/user/deployment/pages/).
So I figured it would be nice to use the feature instead of hacky `before_script`.
As a plus, it will allow us to build pull requests to see if they fail.
> Use travis's first-class deploy to GH pages

- source/guides/1.2/models/overview.md
I've noticed that links go to 404 error page and fixed it
> fixed links in model overview to entities and repositories

- source/guides/1.2/actions/exposures.md
I found this a bit confusing as the guide currently makes it sound a bit like it works by passing instance variables to the view, but actually it works with any method of the given name and only creates an `attr_reader` if a method doesn't already exist. Does this make sense? If so, should it also be applied to the 1.1 and 1.0 articles?
> Make the behaviour of exposures more clear

- source/guides/1.3/repositories/postgresql.md
Official pg docs suggest using `pgcrypto` over `uuid-ossp` because the
`ossp` library is not well maintained.
https://www.postgresql.org/docs/10/static/uuid-ossp.html
> Favor pgcrypto over uuid-ossp

- source/_mailing_list.erb
Opening https://hanamirb.org triggers a non-secure errors. The cause is the ML form.
> Use HTTPS for the mailing list form

- source/layouts/home.erb
- source/stylesheets/application-minimal.css
I felt this could stand to have some margin, and I'm not a big fan of the `<br>`.
Before:
After:
> Remove <br> and add margin-top to release date

- source/stylesheets/application-minimal.css
I noticed this gap and can't see a reason for this CSS rule
Before:
After:
> Remove pointless CSS rule

- config.rb
- source/_footer.erb
- source/layouts/home.erb
Current versions of Firefox, Chrome and Edge already supports native lazy loading, and [Safari is coming too](https://blog.josephscott.org/2019/09/30/safari-is-working-on-native-lazy-loading-images/).
https://web.dev/native-lazy-loading/
> Use native lazy loading on images

- source/blog/2018-10-24-announcing-hanami-130.html.markdown
The name of the method deprecated in v1.3.0 has a typo - it's actually `Hanami::Action#parsed_request_body` (deprecated [here](https://github.com/hanami/controller/commit/06c79e237d37c19fe26a310dd51acc21cf36f98d)).
> Fix name of deprecated method in v1.3.0 release notes

- source/blog/2018-10-24-announcing-hanami-130.html.markdown
This was my bad - when the deprecated method name was updated in 0f39c61f, Markdown started treating the underscores in `parsed_request_body` as italics.  Escaped the underscores. Tested this by running `bin/site build` locally and the section title shows up correctly. Sorry for the noise!
> Fix incorrectly italicized title in v1.3.0 release notes

- source/_lotus.erb
Somehow, the link ending with `.html` is not working. Just fixing it
> Update lotus announcement link

- source/blog/2021-05-04-announcing-hanami-200alpha2.html.markdown
I think that the missed word is "application", however it will make a tautology. Thus, I propose to correct the typo and make a little change for the sentence structure.
> Fix a little typo in Announcing Hanami v2.0.0.alpha2
